# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.3

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/tizwarp/Projects/zen_ecs

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/tizwarp/Projects/zen_ecs

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/tizwarp/Projects/zen_ecs/CMakeFiles /home/tizwarp/Projects/zen_ecs//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/tizwarp/Projects/zen_ecs/CMakeFiles 0
.PHONY : all

# The main codegen target
codegen: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/tizwarp/Projects/zen_ecs/CMakeFiles /home/tizwarp/Projects/zen_ecs//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 codegen
	$(CMAKE_COMMAND) -E cmake_progress_start /home/tizwarp/Projects/zen_ecs/CMakeFiles 0
.PHONY : codegen

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -P /home/tizwarp/Projects/zen_ecs/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ZECS

# Build rule for target.
ZECS: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ZECS
.PHONY : ZECS

# fast build rule for target.
ZECS/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ZECS.dir/build.make CMakeFiles/ZECS.dir/build
.PHONY : ZECS/fast

#=============================================================================
# Target rules for targets named test_ecs

# Build rule for target.
test_ecs: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_ecs
.PHONY : test_ecs

# fast build rule for target.
test_ecs/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ecs.dir/build.make CMakeFiles/test_ecs.dir/build
.PHONY : test_ecs/fast

src/zecs.o: src/zecs.cpp.o
.PHONY : src/zecs.o

# target to build an object file
src/zecs.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ZECS.dir/build.make CMakeFiles/ZECS.dir/src/zecs.cpp.o
.PHONY : src/zecs.cpp.o

src/zecs.i: src/zecs.cpp.i
.PHONY : src/zecs.i

# target to preprocess a source file
src/zecs.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ZECS.dir/build.make CMakeFiles/ZECS.dir/src/zecs.cpp.i
.PHONY : src/zecs.cpp.i

src/zecs.s: src/zecs.cpp.s
.PHONY : src/zecs.s

# target to generate assembly for a file
src/zecs.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ZECS.dir/build.make CMakeFiles/ZECS.dir/src/zecs.cpp.s
.PHONY : src/zecs.cpp.s

tests.o: tests.cpp.o
.PHONY : tests.o

# target to build an object file
tests.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ecs.dir/build.make CMakeFiles/test_ecs.dir/tests.cpp.o
.PHONY : tests.cpp.o

tests.i: tests.cpp.i
.PHONY : tests.i

# target to preprocess a source file
tests.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ecs.dir/build.make CMakeFiles/test_ecs.dir/tests.cpp.i
.PHONY : tests.cpp.i

tests.s: tests.cpp.s
.PHONY : tests.s

# target to generate assembly for a file
tests.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ecs.dir/build.make CMakeFiles/test_ecs.dir/tests.cpp.s
.PHONY : tests.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... codegen"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... ZECS"
	@echo "... test_ecs"
	@echo "... src/zecs.o"
	@echo "... src/zecs.i"
	@echo "... src/zecs.s"
	@echo "... tests.o"
	@echo "... tests.i"
	@echo "... tests.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -P /home/tizwarp/Projects/zen_ecs/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

